import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useSingleWebviewRouter } from '@/page-src/one-webview-poc/use-single-webview-router'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useSingleWebviewRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <button
          type='button'
          onClick={() => {
            router.push(`one-webview-poc`)
          }}>
          webview test
        </button>
      </main>
    </>
  )
}
