import Head from 'next/head'
import Image from 'next/image'

import { useSingleWebviewRouter } from '@/page-src/one-webview-poc/use-single-webview-router'

export default function Home() {
  const router = useSingleWebviewRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <button
          type='button'
          onClick={() => {
            router.push(`swipe-poc`)
          }}>
          swipe test
        </button>
      </main>
    </>
  )
}
